### ISSUE TITLE
Error while upgrading redmine 2.3.3 to 3.0.1

### ISSUE THREAD

**Issue by igroykt** [Undev/redmine_tagging#54]
rake aborted!
NoMethodError: undefined method `include?' for nil:NilClass
/opt/wwwservices/redmine/www/plugins/redmine_tagging/init.rb:8:in `block in <top (required)>'
/opt/wwwservices/redmine/www/config/environment.rb:14:in `<top (required)>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)

**Comment by Boldie** [comment]
Same issue while trying to use 3.0.3 on ruby 2.1.2p95

**Comment by joechang316** [comment]
The redmine 3.1 has the same issue.

**Comment by alincalinciuc** [comment]
Same problem here.

**Comment by hongsoog** [comment]
Redmine 3.1.0 has same issue.

**Comment by amiraliakbari** [comment]
Same error

**Comment by bartlomiejborzucki** [comment]
same error

**Comment by DonnerJack** [comment]
same problem...

**Comment by igroykt** [comment]
@DonnerJack there is a link on working plugin
https://github.com/ixti/redmine_tags/issues/104
but it have a limit in 4 tags per issue

**Comment by nodecarter** [comment]
Have added redmine 3 compatibility.
